version: '3.7'

services:
  cloudy:
    build:
      context: ./
      dockerfile: ./TestWebsite/Dockerfile
    networks:
      - bridge-network

  cypresstests:
    build:
      context: ./cypress.io
      dockerfile: Dockerfile
    networks:
      - bridge-network

networks:
  bridge-network:
    driver: bridge