name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run Cypress tests
      run: docker-compose up --abort-on-container-exit
    
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: dotnet restore
      run: dotnet restore
    - name: npm build
      run: cd Cloudy.CMS.UI/wwwroot-src && npm ci && npm run build
    - name: dotnet build
      run: dotnet build --no-restore
    - name: dotnet test
      run: dotnet test --no-build --verbosity normal
    - name: dotnet pack
      run: dotnet pack --no-build
    - name: nuget publish
      env:
        NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}
      run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key $NUGET_APIKEY --skip-duplicate

