name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run Cypress tests
      run: docker-compose up --abort-on-container-exit
    
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: dotnet restore
      run: dotnet restore
    - name: npm install
      run: cd Cloudy.CMS.UI/wwwroot && npm ci
    - name: npm test
      run: cd Cloudy.CMS.UI/wwwroot && npm run test
    - name: npm cleanup
      run: cd Cloudy.CMS.UI/wwwroot && rm -rf test
    - name: dotnet build
      run: dotnet build --no-restore
    - name: dotnet test
      run: dotnet test --no-build --verbosity normal
    - name: dotnet pack
      run: dotnet pack --no-build
    - name: nuget publish
      env:
        NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}
      run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key $NUGET_APIKEY --skip-duplicate
    - name: Post pipeline job status to Slack
      if: always()
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: 'C04KXEF19PX'
        slack-message: "Pipeline failed (status: ${{ job.status }})\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
